Feat: Best Practices Section
vtex-sites/nextjs.store pull request #101
Opened 2022-06-06 20:45 UTC by renatamottam

## What's the purpose of this pull request?
Following [Fanny's suggestion](https://github.com/vtex-sites/nextjs.store/pull/94#discussion_r889175592), we decided to create a Best Practices section that will first be used at `Alert` doc page.

Also, I updated `Alert` doc page to use `TokenTable`and suggested a new `valueGlobal` prop for when we need to reference a color that's different from `value` prop.

## How does it work?
When needed, you can import `BestPractices` and `BestPracticesRule` from `'src/../.storybook/components'` and use it on your `stories.mdx`:
```
<BestPractices>
  <BestPracticesRule
    recommendedUsage={<RecommendedComponentExample />}
    recommendedDescription="..."
    discouragedUsage={<DiscouragedComponentExample />}
    discouragedDescription="..."
  />
</BestPractices>
```

The result should be something like this:

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/11613011/172245959-ad2fe228-cb69-4b17-85c6-4941ac246561.png">

## How to test it?
You can see and usage example on [Alert doc page](https://nextjs-store-storybook-git-feat-best-practices-504117-faststore.vercel.app/?path=/docs/molecules-alert--default-story#dos-and-donts).

## References
https://style.monday.com/?path=/docs/feedback-alertbanner--overview

## Checklist

**Changelog**
- [x] Added an entry in the `CHANGELOG.md` at the beginning of its due section. [The latest version should comes first](https://keepachangelog.com/en/1.0.0/#:~:text=The%20latest%20version%20comes%20first.).
- [x] Added the PR number with the PR link at the entry in the `CHANGELOG.md`. E.g., *New items in the `pull_request_template.md` ([#4](https://github.com/vtex-sites/nextjs.store/pull/4))* 

**PR Description**
- [x] Added a label according to the PR goal - `Breaking change`, `Enhancement`, `Bug` or `Chore`.

**Documentation**
- [x] PR description
- [x] Added to/Updated the Storybook - *if applicable*.
- [x] For documentation changes, ping @ carolinamenezes, @ PedroAntunesCosta or @ Mariana-Caetano to review and update.

2022-06-06 21:39 UTC, hellofanny commented on .storybook/components/BestPracticesRule.tsx
> +  componentBad: ReactNode
```suggestion
  discourageUsage: ReactNode
```

2022-06-06 21:41 UTC, hellofanny commented on .storybook/components/TokenRow.tsx
> +  valueGlobal,
```suggestion
  globalValue,
```

2022-06-06 22:28 UTC, eduardoformiga reviewed
Awesome! we should add a Renatinha full-stack stamp here hahah

Left some minor comments.

2022-06-06 22:28 UTC, eduardoformiga commented on .storybook/components/BestPractices.tsx
> +const BestPractices = ({ children }: BestPracticesProps) => {
Hmm, what do you think about using `PropsWithChildren`?

```suggestion
import React from 'react'
import type { PropsWithChildren } from 'react'

type BestPracticesProps = {
  title?: string
  description?: string
}

const BestPractices = ({ children }: PropsWithChildren<BestPracticesProps>) => {
```

2022-06-06 22:28 UTC, eduardoformiga commented on .storybook/components/TokenRow.tsx
> +          <div style={{ backgroundColor: valueGlobal ? valueGlobal : value }} />
if you agree with @hellofanny's suggestion, make sure to update here as well :)

2022-06-07 13:49 UTC, ArthurTriis1 commented on .storybook/components/TokenRow.tsx
> +  valueGlobal,
I think globalValue is just used in backgroundColor right? So can we call this prop "colorValue"? If yes, we can change the logic to show the color also. Like this: 

```jsx
{ ( isColor || colorValue ) && (
  <div style={{ backgroundColor: colorValue ? colorValue : value }} />
)}
```

2022-06-07 21:47 UTC, Mariana-Caetano requested changes
Awesome, Renatinha! 🚀
I left some suggestions and comments.

2022-06-07 21:47 UTC, Mariana-Caetano commented on src/components/ui/Alert/Alert.stories.mdx
> +    discouragedDescription="Don't use really long texts. Some important information can be lost."
```suggestion
    discouragedDescription="Don't use long texts. Important information can be lost."
```

2022-06-07 21:47 UTC, Mariana-Caetano commented on src/components/ui/Alert/Alert.stories.mdx
> +    discouragedDescription="Don't use really long texts. Some important information can be lost."
What about defining a character limit for the text? Maybe something around 30 - 40 characters. So the person knows that something over that limit is considered a long text.

2022-06-07 21:47 UTC, Mariana-Caetano commented on src/components/ui/Alert/Alert.stories.mdx
> +    recommendedDescription="Prefer short messages to inform about a behavior of a system, feature or page."
```suggestion
    recommendedDescription="Write short messages to inform about the behavior of a system, feature, or page."
```

2022-06-07 23:30 UTC, hellofanny approved these changes

2022-06-08 14:05 UTC, lucasfp13 commented on .storybook/components/TokenRow.tsx
> +  valueGlobal,
yeah, both `value` and `colorValue` as optional props

2022-06-08 14:08 UTC, lucasfp13 approved these changes
Looks great, nice doc improvement ⭐

2022-06-08 18:05 UTC, Mariana-Caetano approved these changes

2022-06-08 18:22 UTC, merged