Feat: adds tokens to `PriceRange`
vtex-sites/nextjs.store pull request #146
Opened 2022-06-23 21:12 UTC by renatamottam

## What's the purpose of this pull request?

<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>

## How does it work?

<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?

<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em>

## References

<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>

<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>

## Checklist

<em>You may erase this after checking them all ;)</em>

**Changelog**
- [ ] Added an entry in the `CHANGELOG.md` at the beginning of its due section. [The latest version should comes first](https://keepachangelog.com/en/1.0.0/#:~:text=The%20latest%20version%20comes%20first.).
- [ ] Added the PR number with the PR link at the entry in the `CHANGELOG.md`. E.g., *New items in the `pull_request_template.md` ([#4](https://github.com/vtex-sites/nextjs.store/pull/4))* 

**PR Description**
- [ ] Added a label according to the PR goal - `Breaking change`, `Enhancement`, `Bug` or `Chore`.
- [ ] Added the component, hook, or pathname in-between backticks (``) *- If applicable*. E.g., *`ComponentName` component*.
- [ ] Identified the function or parameter in the PR *- If applicable*. E.g., *`useWindowDimensions` hook*.

**Documentation**
- [ ] PR description
- [ ] Added to/Updated the Storybook - *if applicable*.
- [ ] For documentation changes, ping @ carolinamenezes, @ PedroAntunesCosta or @ Mariana-Caetano to review and update.

2022-07-19 13:54 UTC, ArthurTriis1 approved these changes

2022-07-19 13:54 UTC, ArthurTriis1 commented on src/components/ui/PriceRange/PriceRange.stories.mdx
> +    selected: 90,
Could you omit the "testId" property? Also, I think we aren't showing "className" and "aria-label".

2022-07-19 13:54 UTC, ArthurTriis1 commented on src/components/ui/PriceRange/price-range.module.scss
> +  --fs-price-range-selection-bkg-color      : var(--fs-color-primary-bkg-light);
Maybe slider-selection gets more semantic?
```suggestion
  --fs-price-range-slider-selection-bkg-color      : var(--fs-color-primary-bkg-light);
```

2022-07-19 13:54 UTC, ArthurTriis1 commented on src/components/ui/PriceRange/price-range.module.scss
>    [data-store-slider] {
Shouldn't we change this data-attributes to the pattern data-fs?

2022-07-22 21:03 UTC, eduardoformiga reviewed
The layout looks great!

I was playing around a little and maybe I might understand some requirements wrong. But in my opinion, we need to tweak a little:

![GUAlkRljB1](https://user-images.githubusercontent.com/11325562/180567948-08964aeb-20d1-496c-b262-22cb68309ef6.gif)

1. The `thumbs` values are overlapping.
2. Values are not synced between `Slider` and `Inputs`.
3. The `Input` is breaking its width.
<img width="343" alt="Screen Shot 2022-07-22 at 17 55 53" src="https://user-images.githubusercontent.com/11325562/180567403-29307a1d-06bc-44ac-a770-1906d97067bc.png">

4. Decimal values with 4 numbers sometimes inside the `Inputs`.
5. Changing the values on `Inputs` is not firing the `Filter`, only on `Slider` changes.

2022-07-22 21:04 UTC, eduardoformiga commented on src/components/ui/PriceRange/PriceRange.stories.mdx
> +    selected: 90,
Agreed!

2022-07-26 18:38 UTC, renatamottam commented on src/components/ui/PriceRange/price-range.module.scss
>    [data-store-slider] {
We can't :( it's all from FSUI

2022-07-26 18:52 UTC, renatamottam commented on src/components/ui/PriceRange/PriceRange.stories.mdx
> +    selected: 90,
Removed `testId` and `className`, but left `aria-label` cuz we show it on other components such as `Button`.

2022-07-27 20:23 UTC, ArthurTriis1 commented
I found a little problem when the step is changed. The input up/down button aren't following  the step
![priceRange](https://user-images.githubusercontent.com/51174217/181364958-5bb1057e-6c52-4d67-9332-afd69fb37dce.gif)

2022-07-28 04:14 UTC, hellofanny commented on src/components/ui/PriceRange/price-range.module.scss
> +  // Absolute Values
Maybe we could call it 'Disabled Values' since we can use it also when the input is disabled.

2022-07-28 04:17 UTC, hellofanny commented on src/components/ui/PriceRange/price-range.module.scss
> +  --fs-price-range-thumb-border-width         : var(--fs-border-width);
```suggestion
  --fs-price-range-thumb-size                 : var(--fs-price-range-value-label-bottom);
  --fs-price-range-thumb-radius               : var(--fs-border-radius-circle);
  --fs-price-range-thumb-bkg-color            : var(--fs-color-primary-bkg);
  --fs-price-range-thumb-bkg-color-hover      : var(--fs-color-primary-bkg-hover);
  --fs-price-range-thumb-border-width         : var(--fs-border-width);
  --fs-price-range-thumb-border-color         : var(--fs-price-range-thumb-bkg-color);
  --fs-price-range-thumb-border-color-hover   : var(--fs-price-range-thumb-bkg-color-hover);
```

2022-07-28 04:33 UTC, hellofanny requested changes
I noticed that the thumb indicator is not right when adding values (through input fields) that doesn't increase by the amount pre-set on the step (10).  Maybe we need different way to handle it.

![Screenshot (11)](https://user-images.githubusercontent.com/3356699/181419792-ce8fd48f-ddd7-4356-a1b2-ccfc79c4e4a3.png)

Regarding the overlapping values labels:
![Screenshot (13)](https://user-images.githubusercontent.com/3356699/181420651-7698fdf1-41bc-4154-bc82-397345c6e403.png)

- Maybe remove the "absolute values"? Or place it somewhere else? Or increase the contrast?

2022-07-29 05:17 UTC, hellofanny commented
- Are we only displaying the values on hover? I prefer to keep them visible and hide the absolute values ($0 an $100)
- Question: Can this component be used without the input fields? 

![Screenshot (14)](https://user-images.githubusercontent.com/3356699/181679540-c05cb20f-e91d-4a16-9e27-f479b713f569.png)

2022-08-01 17:52 UTC, filipewl approved these changes
Awesome job!

Left some minor comments, but once they're solved this has my approval.

2022-08-01 17:52 UTC, filipewl commented on CHANGELOG.md
> +* Applies new local tokens to `PriceRange` ([#146](https://github.com/vtex-sites/nextjs.store/pull/146))
After some recent changes from https://github.com/vtex-sites/nextjs.store/pull/184, we don't need to manually update the changelog anymore!

When this PR is merged, the PR's title will automatically become the changelog entry, so you may want to rename the PR from "Feat: adds tokens to PriceRange" to "feat: Applies new local tokens to `PriceRange`" if you want to keep this wording.

```suggestion
```

2022-08-01 17:52 UTC, filipewl commented on src/components/ui/PriceRange/PriceRange.stories.mdx
> +    value="var(--fs-border-radius-pill)"
Are we missing a token row for `fs-price-range-margin-bottom`?

2022-08-01 17:52 UTC, filipewl commented on src/components/ui/PriceRange/PriceRange.stories.mdx
> +    value="var(--fs-spacing-4)"
According to the SCSS file:
```suggestion
    value="var(--fs-spacing-3)"
```

2022-08-01 17:52 UTC, filipewl commented on src/components/ui/PriceRange/PriceRange.stories.mdx
> +    globalValue="var(--fs-color-primary-bkg-active)"
According to the SCSS:
```suggestion
    globalValue="var(--fs-color-primary-bkg)"
```

2022-08-01 20:02 UTC, filipewl approved these changes

2022-08-02 20:07 UTC, merged