Feat: adds tokens to `Footer`
vtex-sites/nextjs.store pull request #155
Opened 2022-07-04 13:35 UTC by renatamottam

## What's the purpose of this pull request?
This PR applies the new [Theming structure](https://github.com/vtex-sites/base.store/pull/407) to `ProductGrid`: new scoped tokens linked to global ones.

## How does it work?
This PR uses local variables to parameterize the `ProductGrid` properties, then connects these scoped tokens to the global ones.

## How to test it?

<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em>

## References

<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>

<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>

## Checklist

<em>You may erase this after checking them all ;)</em>

**Changelog**
- [ ] Added an entry in the `CHANGELOG.md` at the beginning of its due section. [The latest version should comes first](https://keepachangelog.com/en/1.0.0/#:~:text=The%20latest%20version%20comes%20first.).
- [ ] Added the PR number with the PR link at the entry in the `CHANGELOG.md`. E.g., *New items in the `pull_request_template.md` ([#4](https://github.com/vtex-sites/nextjs.store/pull/4))* 

**PR Description**
- [ ] Added a label according to the PR goal - `Breaking change`, `Enhancement`, `Bug` or `Chore`.
- [ ] Added the component, hook, or pathname in-between backticks (``) *- If applicable*. E.g., *`ComponentName` component*.
- [ ] Identified the function or parameter in the PR *- If applicable*. E.g., *`useWindowDimensions` hook*.

**Documentation**
- [ ] PR description
- [ ] Added to/Updated the Storybook - *if applicable*.
- [ ] For documentation changes, ping @ carolinamenezes, @ PedroAntunesCosta or @ Mariana-Caetano to review and update.

2022-07-06 22:02 UTC, eduardoformiga reviewed
Good Job! ✨ ✨ 

I noticed some discrepancies comparing with https://nextjs.vtex.app/
![fDyc2YEEV3](https://user-images.githubusercontent.com/11325562/177650669-fa187e9c-a24d-47e7-a4cf-d33a92c83e80.gif)
 
Is that intentional?

I left some comments along the review, and I'm also in doubt if makes sense to use local tokens in some `margin`/`padding` values. So it's up to you hahah

2022-07-08 14:30 UTC, ArthurTriis1 approved these changes
LGTM!

2022-07-08 14:43 UTC, victorhmp requested changes

2022-07-08 14:43 UTC, victorhmp commented on src/components/common/Footer/Footer.tsx
> +export default Footer
This call to `mark(Footer)` alone would have no effect. 

This is confusing hahahah but the `mark` function returns another function, and we need the returned function to run. In this case, I think we need to keep exporting the return from `mark(Footer)`, which will be called when React renders the Footer.

2022-07-08 14:43 UTC, victorhmp commented on src/components/sections/Incentives/incentivesMock.js
> +export const incentivesMockHeader = [
Bit of a nitpick, but why not make this file `.ts`?

2022-07-08 15:38 UTC, eduardoformiga commented on src/components/sections/Incentives/incentivesMock.js
> +export const incentivesMockHeader = [
Yeah, `.ts` would be good.

2022-07-08 15:46 UTC, eduardoformiga commented on src/components/common/Footer/Footer.tsx
> +export default Footer
That's because when we use the `return mark(Footer)`, the storybook becomes a little lost and didn't get the correct description from the component inside the `ArgsTable`. 
<img width="1338" alt="Screen Shot 2022-07-08 at 12 40 26" src="https://user-images.githubusercontent.com/11325562/178025347-d7eea272-b969-4ec0-9616-0ca0412f13b6.png">
https://nextjs-store-storybook-1vu26eycs-faststore.vercel.app/?path=/docs/organisms-footer--footer

And, as we have [an integration test to get marked](https://github.com/vtex-sites/nextjs.store/blob/main/cypress/integration/performance.test.js#L36) `Footer` that still working, we found this solution appropriate. What do you think?

2022-07-08 18:05 UTC, victorhmp commented on src/components/common/Footer/Footer.tsx
> +export default Footer
Uuuhm, that's interesting! I didn't expect it to work 🤔 
Well, in that case, that's fine 😄

2022-07-08 18:05 UTC, victorhmp approved these changes

2022-07-11 21:07 UTC, merged