Feat: Adds tokens to `ProductTitle`
vtex-sites/nextjs.store pull request #84
Opened 2022-06-01 21:33 UTC by eduardoformiga

## What's the purpose of this pull request?

This PR applies the new [Theming structure](https://github.com/vtex-sites/base.store/pull/407) to `ProductTitle`: new scoped tokens linked to global ones.

## How does it work?

This PR uses local variables to parameterize the `ProductTitle` properties, then connects these scoped tokens to the global ones.

### New local tokens for `ProductTitle`

| Local token                                 | Default value/Global token linked          |
| ------------------------------------------- | ------------------------------------------ |
| <code>--fs-product-title-font-size</code>   | <code>var(--fs-text-size-4)</code>         |
| <code>--fs-product-title-font-weight</code> | <code>var(--fs-text-weight-regular)</code> |
| <code>--fs-product-title-line-height</code> | <code>1.12</code>                          |

### Nested Elements

### Addendum

| Local token | Default value/Global token linked |
| - | -|
| <code>--fs-product-title-addendum-margin-top</code> | <code>var(--fs-spacing-3)</code>|
| <code>--fs-product-title-addendum-color</code>      | <code>var(--fs-color-text-light)</code> |

## How to test it?

- The `ProductTitle` component and its variants should look just as it was before these changes.
- You can check the story on Storybook.

## Checklist

<em>You may erase this after checking them all ;)</em>

- [x] Added an entry in the `CHANGELOG.md` at the beginning of its due section. [The latest version should comes first](https://keepachangelog.com/en/1.0.0/#:~:text=The%20latest%20version%20comes%20first.).
- [x] Added the PR number with the PR link at the entry in the `CHANGELOG.md`. E.g., *New items in the `pull_request_template.md` ([#4](https://github.com/vtex-sites/nextjs.store/pull/4))* 

- PR description
- [x] Updated the Storybook - *if applicable*.
- [x] Added a label according to the PR goal - `Breaking change`, `Enhancement`, `Bug` or `Chore`.
- [x] Added the component, hook, or pathname in-between backticks (``) *- If applicable*. E.g., *`ComponentName` component*.
- [x] Identified the function or parameter in the PR *- If applicable*. E.g., *`useWindowDimensions` hook*.
- [x] For documentation changes, ping @ carolinamenezes, @ PedroAntunesCosta or @ Mariana-Caetano to review and update.

2022-06-01 22:55 UTC, hellofanny commented on src/components/ui/ProductTitle/ProductTitle.tsx
> +    <div className={styles.fsProductTitle}>
```suggestion
    <header className={styles.fsProductTitle}>
```

I think we could take the opportunity to update this tag 🙇‍♀️

2022-06-01 22:58 UTC, hellofanny commented on src/components/ui/ProductTitle/ProductTitle.tsx
> +        <div data-fs-product-title-ref-number className="text__legend">
Maybe we should keep using `data-fs-product-title-addendum` to include more generic info. 🤔

2022-06-01 22:59 UTC, hellofanny commented on src/components/ui/ProductTitle/ProductTitle.tsx
> +        <div data-fs-product-title-ref-number className="text__legend">
```suggestion
        <span data-fs-product-title-ref-number className="text__legend">
```

2022-06-01 23:00 UTC, hellofanny commented on src/components/ui/ProductTitle/ProductTitle.tsx
>          </div>
```suggestion
        </span>
```

2022-06-01 23:00 UTC, hellofanny commented on src/components/ui/ProductTitle/product-title.module.scss
> +  // Design Tokens for Checkbox
```suggestion
  // Design Tokens for ProductTile
```

2022-06-01 23:03 UTC, eduardoformiga commented on src/components/ui/ProductTitle/product-title.module.scss
> +  // Design Tokens for Checkbox
oh noh!

2022-06-01 23:05 UTC, hellofanny commented on src/components/ui/ProductTitle/product-title.module.scss
> +    // title prop
```suggestion
    // Title prop
```

2022-06-01 23:06 UTC, hellofanny commented on src/components/ui/ProductTitle/product-title.module.scss
> +    // title prop
hmm actually, thinking if there is other way to select this prop instead of using `&:first-child` 🤔

2022-06-01 23:13 UTC, eduardoformiga commented on src/components/ui/ProductTitle/ProductTitle.tsx
> +        <div data-fs-product-title-ref-number className="text__legend">
At first sight, I agreed. But after I noticed that it needs to be a `div` so that we can apply `margin-top` [here](https://github.com/vtex-sites/nextjs.store/blob/feat/theming-product-title-fsss-378/src/components/ui/ProductTitle/product-title.module.scss#L43).

What do you think?

2022-06-01 23:14 UTC, eduardoformiga commented on src/components/ui/ProductTitle/ProductTitle.tsx
>          </div>
Please,  take a look at the previous comment regarding the `margin-top` ;)

2022-06-01 23:17 UTC, eduardoformiga commented on src/components/ui/ProductTitle/ProductTitle.tsx
> +        <div data-fs-product-title-ref-number className="text__legend">
Hmm, what if we change to `addendum` after we have more things to include? looks like an early improvement.
Thinking on that as well hahah

2022-06-01 23:23 UTC, eduardoformiga commented on src/components/ui/ProductTitle/ProductTitle.tsx
> +    <div className={styles.fsProductTitle}>
Completely agree! done [here](https://github.com/vtex-sites/nextjs.store/pull/84/commits/a5af6985024f41aa176ac8c7b9ea919f0ebd5f4c)

2022-06-01 23:29 UTC, eduardoformiga commented on src/components/ui/ProductTitle/product-title.module.scss
> +    // title prop
That's true! I was thinking about that as well.

Since we pass it as props and we don't have a wrapper. I've found this way to select since the title is required, it should work. But looks a little weird in my opinion. Not sure about the best approach to it. Toughts?

2022-06-02 14:24 UTC, hellofanny commented on src/components/ui/ProductTitle/ProductTitle.tsx
> +        <div data-fs-product-title-ref-number className="text__legend">
But it will still be an addendum hahahaha

2022-06-02 16:16 UTC, eduardoformiga commented on src/components/ui/ProductTitle/ProductTitle.tsx
> +        <div data-fs-product-title-ref-number className="text__legend">
`<p>` looks good! done [here](https://github.com/vtex-sites/nextjs.store/pull/84/commits/3a13ff136fd992bb8223f91a8229ca1865cffcda)

2022-06-02 17:46 UTC, renatamottam requested changes

2022-06-02 17:46 UTC, renatamottam commented on src/components/ui/ProductTitle/product-title.module.scss
> +  --fs-product-title-font-weight           : var(--fs-text-weight-regular);
```suggestion
  --fs-product-title-text-size             : var(--fs-text-size-4);
  --fs-product-title-text-weight           : var(--fs-text-weight-regular);
```

2022-06-02 17:46 UTC, renatamottam commented on src/components/ui/ProductTitle/ProductTitle.tsx
> +    <header className={styles.fsProductTitle}>
```suggestion
    <header data-fs-product-title className={styles.fsProductTitle}>
```

2022-06-03 21:29 UTC, eduardoformiga commented
@renatamottam thanks for reviewing.

The suggestions were implemented [here](https://github.com/vtex-sites/nextjs.store/pull/84/commits/8ba4a120d4c531fa59c12e5f1c09ebf362ea0cac).

2022-06-03 22:34 UTC, eduardoformiga commented on src/components/ui/ProductTitle/ProductTitle.tsx
> +        <div data-fs-product-title-ref-number className="text__legend">
Let's keep `addendum` then! hahah

2022-06-06 12:26 UTC, renatamottam approved these changes
🥳

2022-06-06 12:26 UTC, renatamottam commented on src/components/ui/ProductTitle/product-title.module.scss
> +  --fs-product-title-text-size           : var(--fs-text-size-4);
```suggestion
  --fs-product-title-text-size           : var(--fs-text-size-title-product);
```

2022-06-06 12:27 UTC, renatamottam approved these changes

2022-06-06 12:27 UTC, renatamottam commented on src/components/ui/ProductTitle/ProductTitle.stories.mdx
> +
```suggestion

```

2022-06-06 21:16 UTC, eduardoformiga commented on src/components/ui/ProductTitle/product-title.module.scss
> +    // title prop
As we discuss. We can deal with it when we create the `Heading` component. So I'll resolve this conversation.

2022-06-06 21:34 UTC, hellofanny approved these changes
LGTM!! 🥳🥳🥳

2022-06-06 22:33 UTC, merged